### ISSUE TITLE
Missing Version Bump?

### ISSUE THREAD

**Issue by tobiasmoldan** [0xSiO/bolt-rs#1]
First of all, thanks for creating these crates!

But currently there seems to be a difference between the bolt-client code on docs.rs and this repo even though both have them same version and only the code from here actually builds.

**Comment by 0xSiO** [comment]
Thanks for bringing this to my attention. The build failure appears to be caused by async_native_tls 0.3.3 changing the signature of the `connect` function to accept an `impl Into<Host>` rather than a `&str` and releasing this change as a patch >:(. I've updated the use of this function and released bolt-client v0.5.1.

Please note that this set of libraries is going through major development. I try to follow [SemVer](https://semver.org/) as closely as possible, so for versions 0.X.Y the public API will be unstable. The next release aims to support versions 2 - 4 of the Bolt protocol and Neo4j 4.0. I would advise not to write too much code using bolt-client v0.5 until then.

**Comment by tobiasmoldan** [comment]
Thanks for the quick reply, will go back to http then
